services:
  - type: web
    name: contract-intel
    runtime: python
    region: oregon
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
      python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DEBUG
        value: "False"
