# Generated by Django 5.2.14 on 2026-06-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_document_analysis_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='redaction_summary',
            field=models.JSONField(blank=True, default=dict, help_text="PII redaction counts by type, e.g. {'total_removed': 7, 'by_type': {'PERSON': 3}}"),
        ),
    ]
