# Generated by Django 5.2 on 2026-08-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_document_redaction_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractclause',
            name='legal_context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractclause',
            name='legal_context_sources',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
