# Generated by Django 5.2 on 2026-08-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contractclause_legal_context_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalContextCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_category', models.CharField(max_length=100)),
                ('jurisdiction', models.CharField(max_length=200)),
                ('legal_context', models.TextField()),
                ('sources', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('clause_category', 'jurisdiction'), name='unique_external_context_category_jurisdiction')],
            },
        ),
    ]
